### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by luxlux** [peahonen/pkdl-a1#1]
Good to see there is a non windows solution for this data logger.

But how can i use it? 
I have tried it on mac os 11.2.3. with calling:

`python pkdl_a1.py`

but i got
`Traceback (most recent call last):
  File "/Users/lutz/Documents/Parkside Datalogger - pkdl-a1-master/pkdl_a1.py", line 5, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'`

so i tried `python -m pip install serial`

This was installed:
```
Collecting serial
Downloading serial-0.0.97-py2.py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 kB 1.3 MB/s eta 0:00:00
Collecting pyyaml>=3.13
Downloading PyYAML-6.0.1-cp39-cp39-macosx_10_9_x86_64.whl (197 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.8/197.8 kB 2.9 MB/s eta 0:00:00
Collecting future>=0.17.1
Using cached future-0.18.3-py3-none-any.whl
Collecting iso8601>=0.1.12
Downloading iso8601-2.1.0-py3-none-any.whl (7.5 kB)

Installing collected packages: pyyaml, iso8601, future, serial
Successfully installed future-0.18.3 iso8601-2.1.0 pyyaml-6.0.1 serial-0.0.97
```

But if i try to start it now i get:
```
Traceback (most recent call last):
  File "/Users/lutz/Documents/Parkside Datalogger - pkdl-a1-master/pkdl_a1.py", line 90, in <module>
    sys.exit(main())
  File "/Users/lutz/Documents/Parkside Datalogger - pkdl-a1-master/pkdl_a1.py", line 78, in main
    ser = serial.Serial(args.device)
AttributeError: module 'serial' has no attribute 'Serial'
```
if i ask `which python` i get: `/Users/lutz/opt/miniconda3/bin/python`

So how can i install the needed module?
Or simply how can i run your tool?

**Comment by luxlux** [comment]
Now i tried it with `python -m pip install pyserial==3.5` to install pyserial from your file requirements.txt 
now it worked!
now i can set a correct date, which was even not possible with original windows software.

thanks :)
